# Generated by Django 6.0.3 on 2026-04-02 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strengthexercise',
            name='target_muscle_groups',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
