# Generated by Django 6.0.3 on 2026-04-07 14:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_cardioset_duration_alter_strengthset_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='target_calories',
            field=models.DecimalField(decimal_places=2, default=2000, max_digits=8, validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(10000)]),
            preserve_default=False,
        ),
    ]
