# Generated by Django 6.0.3 on 2026-04-07 23:34

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_customuser_target_calories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardioexercise',
            name='calories_per_minute',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.10')), django.core.validators.MaxValueValidator(Decimal('50.00'))]),
        ),
        migrations.AlterField(
            model_name='cardioset',
            name='duration',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.10')), django.core.validators.MaxValueValidator(Decimal('1440.00'))]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='target_calories',
            field=models.DecimalField(decimal_places=2, default=Decimal('2000.00'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('100.00')), django.core.validators.MaxValueValidator(Decimal('10000.00'))]),
        ),
        migrations.AlterField(
            model_name='foodentry',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.10'))]),
        ),
        migrations.AlterField(
            model_name='strengthset',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.10')), django.core.validators.MaxValueValidator(Decimal('1000.00'))]),
        ),
    ]
