# Generated by Django 6.0.3 on 2026-04-02 15:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_fooditem_calories_alter_fooditem_carbohydrates_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='calories',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2000)]),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='carbohydrates',
            field=models.FloatField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='fat',
            field=models.FloatField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='protein',
            field=models.FloatField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
