# Generated by Django 6.0.3 on 2026-04-02 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_fooditem_calories_alter_fooditem_carbohydrates_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MuscleGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveConstraint(
            model_name='foodentry',
            name='foodentry_unique_entry_per_meal',
        ),
        migrations.RenameField(
            model_name='cardioset',
            old_name='comment',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='cardioset',
            old_name='training',
            new_name='parent_log',
        ),
        migrations.RenameField(
            model_name='foodentry',
            old_name='comment',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='foodentry',
            old_name='food_log',
            new_name='parent_log',
        ),
        migrations.RenameField(
            model_name='strengthset',
            old_name='comment',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='strengthset',
            old_name='training',
            new_name='parent_log',
        ),
        migrations.AlterField(
            model_name='cardioexercise',
            name='name',
            field=models.CharField(max_length=63, unique=True),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='name',
            field=models.CharField(max_length=63, unique=True),
        ),
        migrations.AlterField(
            model_name='strengthexercise',
            name='name',
            field=models.CharField(max_length=63, unique=True),
        ),
        migrations.RemoveField(
            model_name='strengthexercise',
            name='target_muscle_groups',
        ),
        migrations.AddConstraint(
            model_name='foodentry',
            constraint=models.UniqueConstraint(fields=('parent_log', 'meal_type', 'food_item'), name='foodentry_unique_entry_per_meal'),
        ),
        migrations.AddField(
            model_name='strengthexercise',
            name='target_muscle_groups',
            field=models.ManyToManyField(related_name='exercises', to='core.musclegroup'),
        ),
    ]
