# Generated by Django 6.0.3 on 2026-04-21 00:10

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_cardioexercise_calories_per_minute_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strengthset',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('1000.00'))]),
        ),
    ]
