# Generated by Django 6.0.3 on 2026-04-29 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_customuser_activity_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='activity_level',
            field=models.CharField(choices=[('sedentary', 'Sedentary (little or no exercise)'), ('lightly_active', 'Lightly active (light exercise/sports 1-3 days/week)'), ('moderately_active', 'Moderately active (moderate exercise/sports 3-5 days/week)'), ('very_active', 'Very active (hard exercise/sports 6-7 days a week)'), ('extra_active', 'Extra active (very hard exercise/sports & physical job or 2x training)')], default='sedentary', max_length=31),
        ),
    ]
