name: Django CI

on:
  push:
    branches: [ main ]
  pull_request:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
  SECRET_KEY: dummy_secret_key
  DATABASE_URL: postgres://postgres:postgres@localhost:5432/test_db

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_DB: test_db
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        working-directory: backend
        run: |
          pip install -r requirements.txt

      - name: Run migrations
        working-directory: backend/app
        run: |
          python manage.py migrate

      - name: Run tests
        working-directory: backend/app
        run: |
          python manage.py test
